version: "3.3"
services:
  swag:
    image: linuxserver/letsencrypt
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=yomi.eu
      #- SUBDOMAINS=whoami,bookstack,nextcloud,
      - SUBDOMAINS=wildcard
      #- VALIDATION=http
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare #optional
      #- PROPAGATION= #optional
      #- DUCKDNSTOKEN= #optional
      #- EMAIL= #optional
      #- ONLY_SUBDOMAINS=false #optional
      #- EXTRA_DOMAINS= #optional
      #- STAGING=false #optional
    volumes:
      - ${CONFIG}/swag/site-confs/:/config/nginx/site-confs/
      - ${CONFIG}/swag/dns-conf/:/config/dns-conf/
      - ${DATA}/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
    networks:
      - frontend
      - default

  whoami:
    image: "containous/whoami"

networks:
  frontend:
    external:
      name: ${FRONTEND}
