version: '3.5'

services:
  app:
    image: linuxserver/nginx
    container_name: my-identity
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${APPDATA}/my-identity:/config
    restart: unless-stopped
    networks:
      - proxy

  deploy:
    # Modded version in own Dockerfile to fetch google ips
    #image: axiom/rsync-server
    build: .
    environment:
      USERNAME: user
      PASSWORD: ${MY_IDENTITY_RSYNC_PASS} 
      #ALLOW: 0.0.0.0/0
    volumes:
      - ${APPDATA}/my-identity:/data
      - ./my-entrypoint.sh:/my-entrypoint.sh:ro
    ports:
      - "9000:873"
    restart: unless-stopped

networks:
  proxy:
    external: true


