version: '3.5'

services:
  app:
    image: linuxserver/nginx
    container_name: my-identity
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${APPDATA}/my-identity:/config
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-identity.rule=Host(`david-huber.${DOMAIN:?err}`) || Host(`david-huber.eu`) || Host(`www.david-huber.eu`)"
      - "traefik.http.routers.my-identity.entrypoints=websecure"
      - "traefik.http.routers.my-identity.tls.certresolver=leresolver"

      # Some redirects
      # define: david-huber.yomi.eu -> david-huber.eu to keep old links alive
      - "traefik.http.middlewares.my-identity-redirect-yomi.redirectregex.regex=^https://david-huber.${DOMAIN:?err}/(.*)"
      - "traefik.http.middlewares.my-identity-redirect-yomi.redirectregex.replacement=https://david-huber.eu/$${1}"
      - "traefik.http.middlewares.my-identity-redirect-yomi.redirectregex.permanent=true"

      # define: www.david-huber.eu -> david-huber.eu
      - "traefik.http.middlewares.my-identity-redirect-www.redirectregex.regex=^https://www.david-huber.eu/(.*)"
      - "traefik.http.middlewares.my-identity-redirect-www.redirectregex.replacement=https://david-huber.eu/$${1}"
      - "traefik.http.middlewares.my-identity-redirect-www.redirectregex.permanent=true"

      # add redirects
      - "traefik.http.routers.my-identity.middlewares=my-identity-redirect-yomi,my-identity-redirect-www"

  deploy:
    # Modded version in own Dockerfile to fetch google ips
    #image: axiom/rsync-server
    build: .
    environment:
      USERNAME: user
      PASSWORD: ${MY_IDENTITY_RSYNC_PASS} 
      #ALLOW: 0.0.0.0/0
    volumes:
      - ${APPDATA}/my-identity:/data
      - ./my-entrypoint.sh:/my-entrypoint.sh:ro
    ports:
      - "9000:873"
    restart: unless-stopped

networks:
  proxy:
    external: true


secrets:
  rsync_pass:
    file: ${SECRETS:?err}/cf_dns_api_token