version: '3'

services:

  app:
    image: linuxserver/nginx
    container_name: my-identity
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${APPDATA}/my-identity:/config
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
