version: '3.5'

services:
  app:
    image: linuxserver/nginx
    container_name: my-identity
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${APPDATA}/my-identity:/config
    restart: unless-stopped
    networks:
      - proxy

  deploy:
    image: axiom/rsync-server
    environment:
      USERNAME: user
      PASSWORD: ${MY_IDENTITY_RSYNC_PASS} 
      ALLOW: 0.0.0.0/0
    volumes:
      - ${APPDATA}/my-identity:/data
    ports:
      - "9000:873"
    restart: unless-stopped

networks:
  proxy:
    external: true


