version: '3'

services:

  db:
    image: linuxserver/mariadb
    environment:
      - MYSQL_DATABASE=${BOOKSTACK_DB_DATABASE:-bookstack}
      - MYSQL_USER=${BOOKSTACK_DB_USER:-bookstack}
      - MYSQL_PASSWORD=${BOOKSTACK_DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${BOOKSTACK_DB_ROOT_PASSWORD:-supersecret}
      - PUID
      - PGID
      - TZ
    volumes:
      - ${APPDATA}/bookstack/db:/config
    restart: unless-stopped

  app:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - DB_HOST=db
      - DB_DATABASE=${BOOKSTACK_DB_DATABASE:-bookstack}
      - DB_USER=${BOOKSTACK_DB_USER:-bookstack}
      - DB_PASSWORD=${BOOKSTACK_DB_PASSWORD:-secret}
      - APP_URL="https://bookstack.${DOMAIN:-example.org}"
      - PUID
      - PGID
      - TZ
    volumes:
      - ${APPDATA}/bookstack/app:/config
    networks:
      - proxy
      - ldap
      - default
    restart: unless-stopped
    depends_on:
      - db

  db-backup:
    image: mariadb:10
    environment:
      - MYSQL_DATABASE=${BOOKSTACK_DB_DATABASE:-bookstack}
      - MYSQL_USER=${BOOKSTACK_DB_USER:-bookstack}
      - MYSQL_PASSWORD=${BOOKSTACK_DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${BOOKSTACK_DB_ROOT_PASSWORD:-supersecret}
      - PUID
      - PGID
      - TZ
      - BACKUP_FREQUENCY=${MYSQL_BACKUP_FREQUENCY:-1d}
      - BACKUP_NUM_KEEP=${MYSQL_BACKUP_NUM_KEEP:-7}
    volumes:
      - ${APPDATA}/bookstack/db-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 10s
      while /bin/true; do
        mysqldump --single-transaction -h db --all-databases -u $$MYSQL_USER -p$$MYSQL_PASSWORD | gzip -c > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql.gz
        (ls -t /dump/dump*.sql.gz|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.sql.gz)|sort|uniq -u|xargs -r rm
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    depends_on:
      - db

networks:
  proxy:
    external: true
  ldap:
    external: true

