version: '3'

services:

  db:
    image: linuxserver/mariadb
    env_file: ./bookstack.env
    volumes:
      - ${APPDATA}/bookstack/db:/config
    restart: unless-stopped

  app:
    image: linuxserver/bookstack
    env_file: ./bookstack.env
    container_name: bookstack
    volumes:
      - ${APPDATA}/bookstack/app:/config
    networks:
      - proxy
      - default
    restart: unless-stopped
    depends_on:
      - db

networks:
  proxy:
    external: true
