version: "3.5"
services:
  nextcloud:
    container_name: nextcloud
    image: linuxserver/nextcloud
    environment:
      - PUID
      - PGID
      - TZ
    env_file: ./nextcloud.env
    volumes:
      - ${APPDATA}/nextcloud/app/config:/config
      - ${APPDATA}/nextcloud/app/data:/data
    networks:
      - proxy
      - ldap
      - default
    links:
      - db:nextcloud_db
    restart: unless-stopped
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN:?err}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=leresolver"

      # Since this docker image only provides https access
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
      - "traefik.http.services.nextcloud.loadbalancer.server.scheme=https"

      # This didn't work -> enabling insecureSkipVerify globally for traefik instead
      # - "traefik.http.serversTransports.myinsecure.loadbalancer.insecureSkipVerify=true"
      # - "traefik.http.services.nextcloud.loadbalancer.serversTransport=myinsecure"

      # drop redirect
      - "traefik.http.routers.drop.rule=Host(`drop.${DOMAIN}`)"
      - "traefik.http.routers.drop.entrypoints=websecure"
      - "traefik.http.routers.drop.tls.certresolver=leresolver"

      - "traefik.http.middlewares.drop-redirect.redirectregex.regex=^https://drop.yomi.eu/(.*)"
      - "traefik.http.middlewares.drop-redirect.redirectregex.replacement=https://nextcloud.yomi.eu/s/w7iXZ37pJKbsGEi"
      - "traefik.http.middlewares.drop-redirect.redirectregex.permanent=true"
      - "traefik.http.routers.drop.middlewares=drop-redirect"

  db:
    image: linuxserver/mariadb
    env_file: ./nextcloud.env
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${APPDATA}/nextcloud/db:/config
    restart: unless-stopped

  db-backup:
    image: mariadb:10
    env_file: ./nextcloud.env
    environment:
      - PUID
      - PGID
      - TZ
      - BACKUP_FREQUENCY=${MYSQL_BACKUP_FREQUENCY:-1d}
      - BACKUP_NUM_KEEP=${MYSQL_BACKUP_NUM_KEEP:-7}
    volumes:
      - ${APPDATA}/nextcloud/db-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 10m
      while /bin/true; do
        mysqldump --single-transaction -h db --all-databases -u $$MYSQL_USER -p$$MYSQL_PASSWORD | gzip -c > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql.gz
        (ls -t /dump/dump*.sql.gz|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.sql.gz)|sort|uniq -u|xargs -r rm
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    depends_on:
      - db

#  # Debugging
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - db

networks:
  proxy:
    external: true
  ldap:
    external: true

