version: "2.1"
services:
  nextcloud:
    container_name: nextcloud
    image: linuxserver/nextcloud
    environment:
      - PUID
      - PGID
      - TZ
    env_file: ./nextcloud.env
    volumes:
      - ${APPDATA}/nextcloud/app/config:/config
      - ${APPDATA}/nextcloud/app/data:/data
    networks:
      - proxy
      - ldap
      - default
    restart: unless-stopped
    depends_on:
      - nextcloud_db

  nextcloud_db:
    container_name: nextcloud_db
    image: linuxserver/mariadb
    env_file: ./nextcloud.env
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${APPDATA}/nextcloud/db:/config
    restart: unless-stopped

networks:
  proxy:
    external: true
  ldap:
    external: true

