version: '3'

services:
  openldap:
    image: osixia/openldap:1.4.0
    container_name: openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: ${DOMAIN:-example.org} 
      LDAP_DOMAIN: ${DOMAIN:-example.org}
      #LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin}
      #LDAP_CONFIG_PASSWORD: "config"
      #LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "true"
      #LDAP_BACKEND: "mdb"
      LDAP_TLS: "false"
      #LDAP_TLS: "true"
      #LDAP_TLS_CRT_FILENAME: "ldap.crt"
      #LDAP_TLS_KEY_FILENAME: "ldap.key"
      #LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      #LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      #LDAP_TLS_ENFORCE: "false"
      #LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      #LDAP_TLS_VERIFY_CLIENT: "demand"
      #LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$$LDAP_BASE_DN" bindmethod=simple credentials=$$LDAP_ADMIN_PASSWORD searchbase="$$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      #KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      #LDAP_SSL_HELPER_PREFIX: "ldap"
    #tty: true
    #stdin_open: true
    volumes:
      - ${APPDATA}/ldap/var:/var/lib/ldap
      - ${APPDATA}/ldap/slapd.d:/etc/ldap/slapd.d
      - ${APPDATA}/ldap/certs:/container/service/slapd/assets/certs/
    # For replication to work correctly, domainname and hostname must be
    # set correctly so that "hostname"."domainname" equates to the
    # fully-qualified domain name for the host.
    domainname: ${DOMAIN:-example.org}
    hostname: "ldap-server"
    networks:
      - proxy
      - ldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - openldap
    networks:
      - proxy
      - ldap

  lum:
    image: wheelybird/ldap-user-manager:latest
    container_name: lum
    environment:
      SERVER_HOSTNAME: "lum.${DOMAIN}"
      LDAP_URI: "ldap://openldap"
      LDAP_BASE_DN: ${LDAP_BASE_DN:-dc=yomi,dc=eu}
      #LDAP_REQUIRE_STARTTLS: "false"
      #LDAP_TLS_CACERT: "/ldap.crt"
      LDAP_ADMINS_GROUP: "admin"
      LDAP_ADMIN_BIND_DN: "cn=admin,${LDAP_BASE_DN:-dc=yomi,dc=eu}"
      LDAP_ADMIN_BIND_PWD: ${LDAP_ADMIN_PASSWORD:-admin}
      #LDAP_USES_NIS_SCHEMA: "false"
      NO_HTTPS: "true"
    depends_on:
      - openldap
    #volumes:
    #  - ${APPDATA}/ldap/lum/www:/opt/ldap_user_manager/
    #  - ${APPDATA}/ldap/certs/ldap.crt:/ldap.crt
    networks:
      - proxy
      - ldap

networks:
  proxy:
    external: true
  ldap:
    external: true
